sudo: required

language: node_js

services:
  - docker # required, but travis uses older version of docker :(
install:
  - echo "npm install"
script:
  - echo "no tests!" # put your normal testing scripts here

#env vars: GCLOUD_KEY, GCLOUD_EMAIL, PROJECT_NAME_PRD, DOCKER_IMAGE_NAME

cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  
after_success:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  # Auth flow
  - echo $GCLOUD_KEY | base64 --decode > gcloud.p12
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12
  - ssh-keygen -f ~/.ssh/google_compute_engine -N ""
  # build image
  - docker --version
  - docker build -t gcr.io/$PROJECT_NAME_PRD/$DOCKER_IMAGE_NAME:v1 .
  - gcloud --quiet config set project $PROJECT_NAME_PRD
  - gcloud --quiet container clusters get-credentials $PROJECT_NAME_PRD
  - gcloud docker push gcr.io/${PROJECT_NAME_PRD}/${DOCKER_IMAGE_NAME}
